[package]
name = "hashbench-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [] }
jolt-inlines-sha2.workspace = true
jolt-inlines-keccak256.workspace = true
jolt-inlines-blake2.workspace = true
jolt-inlines-blake3.workspace = true

sha2 = { version = "0.10.9", default-features = false }
sha3 = { version = "0.10", default-features = false }
blake2 = { version = "0.10.6", default-features = false }
blake3 = { version = "1.6", default-features = false }