name = "Extracted Jolt circuits"
defaultTargets = ["Jolt"]
testDriver = "Tests"

[[lean_lib]]
name = "Jolt"

[[lean_lib]]
name = "Tests"

[[require]]
name = "zkLean"
git = "https://github.com/GaloisInc/zk-lean.git"
rev = "23cde8a421bcce980f4ef0b4e109524c8033d427"
subDir = "zk_lean"

# TODO: This is present only so we can copy the BN254 scalar field
# from ArkLib. We need to do this because ArkLib doesn't currently
# use the most recent version of Lean. We can replace this
# requirement with ArkLib once that's updated.
[[lean_lib]]
name = "ArkLib"
[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.2"
