[package]
name = "jolt-inlines-keccak256"
version = "0.1.0"
edition = "2021"
description = "Keccak-256 inline implementations for Jolt VM"
license = "MIT"
homepage = "https://github.com/a16z/jolt/README.md"
repository = "https://github.com/a16z/jolt"

[features]
default = []
host = ["dep:ctor", "dep:tracer", "dep:tracing"]

[dependencies]
ctor = { workspace = true, optional = true }
tracer = { workspace = true, optional = true, features = ["std"] }
tracing = { workspace = true, optional = true }

[dev-dependencies]
hex-literal.workspace = true
sha3.workspace = true
tracer = { workspace = true, features = ["std", "test-utils"] }
