[files]
extend-exclude = ["patches/*.patch"]

[default.extend-words]
"groth" = "groth"
"fle" = "fle"
"sie" = "sie"
"stip" = "stip"
"thr" = "thr"
"thre" = "thre"
"numer" = "numer"
"Toom" = "Toom"

[default.extend-identifiers]
"fo" = "fo"
"fo_config" = "fo_config"
"fo_witness" = "fo_witness"
"fo_map" = "fo_map"
"config_with_fo" = "config_with_fo"
