[package]
name = "recursion-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []
cycle-tracking = ["jolt_sdk/cycle-tracking"]

[dependencies]
jolt_sdk = { package = "jolt-sdk", path = "../../../jolt-sdk", features = ["guest-verifier"] }
postcard.workspace = true
ark-serialize.workspace = true
