[package]
name = "advice-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
tracing-subscriber.workspace = true
tracing.workspace = true
guest = { package = "advice-demo-guest", path = "./guest" }
