[package]
name = "sha2-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
jolt-inlines = { path = "../../jolt-inlines", features = ["host", "sha256"] }
guest = { package = "sha2-chain-guest", path = "./guest" }

hex = "0.4.3"
