[package]
name = "sha2-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
tracing-subscriber = "0.3"
tracing = "0.1"
jolt-inlines-sha2 = { path = "../../jolt-inlines/sha2", features = ["host"] }
guest = { package = "sha2-chain-guest", path = "./guest" }

hex = "0.4.3"
