[package]
name = "sha3-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
guest = { package = "sha3-guest", path = "./guest" }
hex = "0.4.3"

[features]
icicle = ["jolt-sdk/icicle"]
