[package]
name = "sha3-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
tracing-subscriber = "0.3"
tracing = "0.1"
jolt-inlines-keccak256 = { path = "../../jolt-inlines/keccak256", features = [
    "host",
] }
guest = { package = "sha3-guest", path = "./guest" }
hex = "0.4.3"
