[package]
name = "advice-demo-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []
compute_advice = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = ["guest-std"] }
