[package]
name = "base64-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt        = { package = "jolt-sdk", path = "../../../jolt-sdk", features = ["guest-std"] }
serde       = { version = "1.0", default-features = false, features = ["derive"] }
serde_bytes = { version = "0.11", default-features = false }