[package]
name = "memory-ops"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
tracing-subscriber.workspace = true
tracing.workspace = true
guest = { package = "memory-ops-guest", path = "./guest" }

hex = "0.4.3"
