[package]
name = "z3-verifier"
edition = "2021"

[dependencies]
paste.workspace = true

jolt-core = { path = "../jolt-core" }
common = { path = "../common" }
tracer = { path = "../tracer" }
z3 = "0.19.2"
