[package]
name = "memory-ops-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
guest = { package = "memory-ops-guest", path = "./guest" }

hex = "0.4.3"
