[package]
name = "verifier-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = ["guest-std"] }
jolt-verifier = { path = "../../../jolt-verifier" }
ark-bn254 = "0.5.0"