[package]
name = "jolt-inlines-grumpkin"
version = "0.1.0"
edition = "2021"
description = "Grumpkin implementations for Jolt VM"
license = "MIT"
homepage = "https://github.com/a16z/jolt/README.md"
repository = "https://github.com/a16z/jolt"

[features]
default = []
host = ["dep:ctor", "dep:tracer", "dep:tracing"]

[dependencies]
ctor = { workspace = true, optional = true }
tracer = { workspace = true, optional = true, features = ["std"] }
tracing = { workspace = true, optional = true }
serde.workspace = true
ark-grumpkin.workspace = true
ark-serialize.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
num-bigint.workspace = true
num-integer.workspace = true

[dev-dependencies]
hex-literal.workspace = true
tracer = { workspace = true, features = ["std", "test-utils"] }
