[package]
name = "recursion"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "recursion"
path = "src/main.rs"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host", "recursion"] }
tracing-subscriber = "0.3"
tracing = "0.1"
ark-serialize = { version = "0.5.0", default-features = false }
postcard = { version = "1.0.8", default-features = false, features = ["use-std"] }
clap = { version = "4.0", features = ["derive"] }
