[package]
name = "hash-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
tracing-subscriber.workspace = true
jolt-inlines-sha2 = { workspace = true, features = ["host"] }
jolt-inlines-keccak256 = { workspace = true, features = ["host"] }
jolt-inlines-blake2 = { workspace = true, features = ["host"] }
jolt-inlines-blake3 = { workspace = true, features = ["host"] }
guest = { package = "hashbench-guest", path = "./guest" }
hex.workspace = true

[package.metadata.cargo-machete]
ignored = ["jolt-inlines-sha2", "jolt-inlines-keccak256", "jolt-inlines-blake2", "jolt-inlines-blake3"]