[package]
name = "sha3-chain-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk" }
jolt-inlines-keccak256.workspace = true
