[package]
name = "sha3-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
tracing-subscriber.workspace = true
tracing.workspace = true
jolt-inlines-keccak256 = { path = "../../jolt-inlines/keccak256", features = [
    "host",
] }
guest = { package = "sha3-guest", path = "./guest" }
hex.workspace = true
