[package]
name = "stdlib-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [
    "guest-std",
] }
# Boot code is now provided by jolt-sdk's guest_std_boot module
# bolt = { path = "/Users/sdhawan/Work/ZeroKernel/crates/bolt", features = ["std", "boot-symbols"] }
