[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[features]
transcript-poseidon = ["jolt-sdk/transcript-poseidon"]
transcript-keccak = ["jolt-sdk/transcript-keccak"]
transcript-blake2b = ["jolt-sdk/transcript-blake2b"]

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
tracing-subscriber.workspace = true
tracing.workspace = true
guest = { package = "fibonacci-guest", path = "./guest" }

