[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
guest = { package = "fibonacci-guest", path = "./guest" }

[features]
icicle = ["jolt-sdk/icicle"]
