[package]
name = "memory-ops-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
sha3 = { version = "0.10.8", default-features = false }
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk" }
