[package]
name = "sha2-chain-advice-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sha2-chain-advice-guest"
path = "src/main.rs"
required-features = ["guest"]

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [] }
jolt-inlines-sha2.workspace = true
