[package]
name = "modexp-chain-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [] }
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
