name: CI Benchmarks

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Performance benchmarks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install RISC-V cross-compiler
        run: sudo apt-get install -y gcc-riscv64-unknown-elf
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/cache@v5 # From: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.zeroos
            ~/.cache/dory
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust-src
        run: rustup component add rust-src

      - name: Build and install jolt CLI
        run: cargo install --path . --locked

      - name: Run benchmark
        run: |
          cd examples
          ./run_ci_benchmarks.sh
          cd ..

      - name: Publish benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmarks
          tool: "customSmallerIsBetter"
          output-file-path: examples/benchmark_results.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
