name: Deploy mdBook to GCS

on:
  push:
    branches:
      - main 

jobs:
  deploy_gcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY}}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'

    - name: Install mdbook-katex
      run: cargo install mdbook-katex

    - run: mdbook build ./book

    - name: Deploy to Google Cloud Storage
      run: gsutil -m rsync -d -r ./book/book gs://${{ secrets.GCS_BUCKET_NAME }}

  deploy_firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
      - name: Install mdbook-katex
        run: cargo install mdbook-katex

      - run: mdbook build ./book

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
          channelId: live
